from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from .clarification import ClarificationManager
from .framework_selector import FrameworkSelector
from .generator import CodeGenerator
from .llm import LLMRequestError, MockLLMClient, MultiLLMClient, resolve_llm_client
from .output import OutputManager
from .planner import Planner
from .validator import Validator


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Agentic Game Builder MVP")
    parser.add_argument("--prompt", help="Initial game idea prompt.")
    parser.add_argument("--output-dir", help="Directory where generated files will be written.")
    parser.add_argument("--answers-file", help="Optional JSON file containing clarification answers.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    prompt = args.prompt or input("Enter a vague game idea: ").strip()
    if not prompt:
        print("A prompt is required.")
        return 1

    try:
        llm_client, llm_note = resolve_llm_client()
    except RuntimeError as error:
        print(f"LLM configuration issue: {error}")
        print("Falling back to deterministic mock LLM client.")
        llm_client = MockLLMClient()
        llm_note = "Using deterministic mock LLM client."

    print("== Agentic Game Builder MVP ==")
    print(llm_note)
    print("\n[Phase 1/5] Clarify")

    clarification_manager = ClarificationManager()
    questions = clarification_manager.build_questions(prompt)
    try:
        provided_answers = _load_answers_file(args.answers_file)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Unable to read answers file: {error}")
        return 1
    answers: dict[str, str] = dict(provided_answers)

    if not questions:
        print("No additional clarification needed. The prompt already contains the minimum implementation details.")
    for question in questions:
        print(f"- {question.reason}")
        answer = provided_answers.get(question.key)
        if answer is None:
            try:
                answer = input(f"{question.prompt} ").strip()
            except EOFError:
                print(
                    f"No answer provided for clarification question '{question.key}'. "
                    "Run interactively or include the missing field in --answers-file."
                )
                return 1
        else:
            print(f"{question.prompt} {answer}")
        if answer:
            answers[question.key] = answer

    print("\n[Phase 2/5] Select Framework")
    framework_decision = FrameworkSelector().select(prompt, answers)
    print(f"Selected framework: {framework_decision.framework}")
    print(f"Reason: {framework_decision.reason}")

    print("\n[Phase 3/5] Plan")
    spec, plan_messages = build_spec_with_fallback(prompt, answers, framework_decision.framework, llm_client)
    plan_renderer = Planner(llm_client=MockLLMClient())
    for message in plan_messages:
        print(message)
    print(plan_renderer.render_plan(spec))

    print("\n[Phase 4/5] Generate")
    generator = CodeGenerator()
    artifacts = generator.generate(spec)
    validator = Validator()
    artifact_validation = validator.validate_artifacts(artifacts)
    for message in artifact_validation.messages:
        print(f"- {message}")
    if not artifact_validation.passed:
        return 1

    output_manager = OutputManager()
    target_dir = output_manager.resolve_target_dir(args.output_dir, spec.title)
    output_manager.write_artifacts(target_dir, artifacts)

    print("\n[Phase 5/5] Validate")
    directory_validation = validator.validate_directory(target_dir)
    for message in directory_validation.messages:
        print(f"- {message}")
    if not directory_validation.passed:
        return 1

    print(f"\nGenerated game saved to: {target_dir}")
    print("Open index.html in a browser to play the game locally.")
    return 0


def _load_answers_file(path: str | None) -> dict[str, str]:
    if not path:
        return {}
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("answers file must contain a JSON object.")
    return {str(key): str(value) for key, value in payload.items()}


def build_spec_with_fallback(
    prompt: str,
    answers: dict[str, str],
    framework: str,
    llm_client: Any,
) -> tuple[Any, list[str]]:
    planner = Planner(llm_client=llm_client)
    try:
        spec = planner.build_spec(prompt, answers, framework=framework)
        if isinstance(llm_client, MultiLLMClient) and llm_client.last_success_label:
            return spec, [f"Live LLM planning copy generated by {llm_client.last_success_label}."]
        return spec, []
    except LLMRequestError as error:
        if isinstance(llm_client, MockLLMClient):
            raise
        fallback_messages = [
            f"Live LLM planning copy failed: {error}",
            "Falling back to deterministic mock LLM client for plan copy so generation can continue.",
        ]
        fallback_planner = Planner(llm_client=MockLLMClient())
        return fallback_planner.build_spec(prompt, answers, framework=framework), fallback_messages


if __name__ == "__main__":
    raise SystemExit(main())
